### ISSUE TITLE
Fast API throwing Internal Server error

### ISSUE THREAD

**Issue by KKodiac** [zeroday0619/COVID-19API#2]
**Describe the bug**
/detail/ api url throwing Internal Server error.

**To Reproduce**
Goto:
https://ncov.zeroday0619.kr/kr/status/inspection/detail

**Expected behavior**
Should return json data of detailed information of current info of Korean Covid-19 patients

**실행 환경:**

 - OS: Linux Ubuntu 18.04.4
 - Python Version: 3.6.9

**Additional context**
이 프로젝트에 기여하고 싶은데 군인이라 연등 밖에 시간이 없네요ㅠㅠ 
좋은 API 제공해줘서 고마워요!!

**Comment by zeroday0619** [comment]
http://ncov.mohw.go.kr/bdBoardList_Real.do?brdGubun=11
질본 페이지 html 구조가 변경 되서 해당 부분 수정 했습니다
