### ISSUE TITLE
Installing requirements gives error

### ISSUE THREAD

**Issue by superjoy0502** [zeroday0619/COVID-19API#4]
`python -m pip install -r requirements.txt`을 실행하였을 때

`Could not find a version that satisfies the requirement fastapi[all] (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for fastapi[all] (from -r requirments.txt (line 1))`가 출력됩니다.

파이썬 버젼: 3.8
OS: Ubuntu 18.04

**Comment by superjoy0502** [comment]
pip install fastapi 역시 안되네요.
이건 fastapi만의 문제인 것 같습니다.

**Comment by zeroday0619** [comment]
@superjoy0502 
`python3 -m pip install fastapi[all]`

Python2 is not supported and python commands on Ubuntu 18.04 LTS run python2

![image](https://user-images.githubusercontent.com/54426648/79189313-61230f00-7e5c-11ea-8505-fc94e46df968.png)

**Comment by superjoy0502** [comment]
Solved.
by executing the command `python3 -m pip install fastapi[all]` it returned "No module named pip".
In order to solve this, I executed the command `sudo apt install python3-pip`, which installed pip for my computer, which was brand new. 
Thanks for the help!
